### ISSUE TITLE
Virtual Functions table header in LXD VM hosts is misleading 

### ISSUE THREAD

**Issue by rayito** [canonical/maas-ui#3923]
The Virtual Functions card in the LXD VM hosts used to look like this:

![image.png](https://images.zenhubusercontent.com/54538a0a7c6ccc6277a5d047/f3df999b-7cc0-43a5-8726-6a38ec70fad2)

After the LXD Cluster work and redesign of the entire UI, it now looks like this:

![image.png](https://images.zenhubusercontent.com/54538a0a7c6ccc6277a5d047/f7f173c9-fcc4-4605-bf04-e01a2d0da429)

@albertodonato pointed out that this is a bit misleading, since the new location of "VF" looks like the column on the left side represents "Virtual Functions", but it actually shows interfaces. For each interface, we show the amount of allocated and free virtual functions.

**Comment by huwshimi** [comment]
It looks like this is in a number of places. With the extra room should they all be changed to "Virtual functions" rather than "VF?
https://app.zeplin.io/project/6143a6443fa54c294b39e16a/screen/615eab206eed772ced8b4043
https://app.zeplin.io/project/6143a6443fa54c294b39e16a/screen/615eab25169e593f54afdceb
https://app.zeplin.io/project/6143a6443fa54c294b39e16a/screen/615eab3f0e47492b3e9b90b3
https://app.zeplin.io/project/6143a6443fa54c294b39e16a/screen/615eab45dbb013438f62f3e2
https://app.zeplin.io/project/6143a6443fa54c294b39e16a/screen/615eab4c30c2efb1a5923b77
https://app.zeplin.io/project/6143a6443fa54c294b39e16a/screen/615eab50af27183e7d129b41

**Comment by rayito** [comment]
I will propose a solution and check with @lyubomir-popov , like moving the title back to where it used to be and adding a table header for `INTERFACES`

**Comment by rayito** [comment]
![Frame 201](https://user-images.githubusercontent.com/5860630/170685421-a7e469bf-f0e2-4a7d-81cd-57e9d3e4ca8a.png)

@lyubomir-popov what do you think about this?

**Comment by anthonydillon** [comment]
This issue is missing an estimate

**Comment by lyubomir-popov** [comment]
@rayito your proposal looks good to me 👍

**Comment by rayito** [comment]
@ndv99
