### ISSUE TITLE
redundant websocket messages sent over the network

### ISSUE THREAD

**Issue by petermakowski** [canonical/maas-ui#4274]
`machine` (e.g. `machine.get`) WebSocket messages with the same payload is sent to the back-end multiple times when loading the machine details/machine listing page (and the back-end comes back with a result each time as expected).

This results in sending completely redundant data over the network and definitely does not help performance. This could be happening to other request types, we should look into it.
 
#### Notes
This also applies to machines lists
![image.png](https://images.zenhubusercontent.com/6110f1cbad9628d5cdec1846/9b329162-a84c-4fc0-bb04-22c3e219b7ac)

`nocache`
https://github.com/canonical-web-and-design/maas-ui/blob/main/src/app/base/sagas/websockets.ts#L575-L576

**Comment by huwshimi** [comment]
Maybe in the hook for getting a machine it should check for whether the machine details exist in the store, or otherwise it could check if there is another request in the store for the same id. We still need to store a details request for each place that is using it so that we know when it is safe to unsubscribe from the machine.

**Comment by petermakowski** [comment]
Closing as this is now being tracked on JIRA.
