### ISSUE TITLE
Filters and Group by are ordered differently

### ISSUE THREAD

**Issue by petermakowski** [canonical/maas-ui#4510]
Filters and Group by are ordered differently

<img width="374" alt="image" src="https://user-images.githubusercontent.com/7452681/197138160-7ce01756-832e-4343-972a-9cdbc576ce20.png">
<img width="449" alt="image" src="https://user-images.githubusercontent.com/7452681/197138181-7e8b525b-67d0-4004-b09b-1bd08fdba0aa.png">

### Question for UX
I suspect there's a reason why we order the filters the way we do (with the status at the top) and the "group by" field should have the same order (instead of alphabetical). 

Please let me know how you'd like me to proceed @amylily1011

**Comment by amylily1011** [comment]
Yes, originally it was ordered by most useful or most popular (I think). We don't need to preserve the same order because as the list grows, it might be hard to navigate if it's not in a uniform order. 

Since there are 7 on the list at the moment, we can go back to the original grouping mechanism, because this is the maximum cognitive load per list. But once we grow out of 7, people won't worry about what's on top anymore, alphabetical order would make it easier for them to find it.
