### ISSUE TITLE
Machine list doesn't move machines between categories when their status changes

### ISSUE THREAD

**Issue by ndv99** [canonical/maas-ui#4709]
**Describe the bug**
When "Group by status" is selected on the machine list and a machine changes status, the machine in question is not regrouped under its new status.

**MAAS version**
3.4.0~alpha1

**To Reproduce**
1. Go to machine listing
2. Ensure machines are grouped by status
3. Select a machine that has failed commissioning 
4. Begin commissioning the machine
5. Machine remains grouped under "Failed commissioning" even though status has changed to "Commissioning"

**Expected behavior**
 When "Group by status" is selected on the machine list and a machine changes status, the machine in question **_is_** regrouped under its new status.

**Screenshots**
A machine that is commissioning but is still under "Failed commissioning"
![image](https://user-images.githubusercontent.com/35104482/214556194-569ae3f4-af2b-4e74-9b69-cf897987b460.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10
 - Browser: Chrome
 - Version: 108.0.5359.124

**Additional context**
Originally reported on Usabilla.

**Comment by petermakowski** [comment]
Thanks for writing up a detailed report @ndv99.

Fixing this will not be trivial as grouping is now done on the back-end. Having looked at the spec one might also conclude that it works as intended.

From the specification:
> "No new machines are added and no existing machines are removed from the list even if the original filter criteria would return a different set of machines later on, e.g. if filtering by “status=New” and one of the machines changes status from New to Commissioning - it stays in the list even though it doesn’t match the original filter criteria.".

https://docs.google.com/document/d/1B8CQXRxzapUq8dbSILzCZdrNzU49brVS8K5KQAZeQiw/edit#heading=h.zigbvs6tfnth

**Comment by tmerten** [comment]
> Having looked at the spec one might also conclude that it works as intended

Maybe this situation just was not foreseen. "stays in the list" != "stays in the group" .

**Comment by tmerten** [comment]
Hey @ndv99 @petermakowski @Jay-Topher @amylily1011 

Here is what has been discussed in the bug council (and took the entire meeting). We know that it is not 100% consistent with the originally intended UX in the spec but we think that it is the best quick fix that is still rather in line with what we decided and at the same time it removes some of the weirdness.
 
> MAAS backend should notify the UI about a change in the requested information, and the UI would update the displayed information based on that notification (option 2.2). The UI would need to issue a new query with the currently shown IDs and ask for grouping, and backend would generate the current status. Requesting the original query again would not be optimal for UX because the operators expect to see the same set of machines when e.g. waiting for them to deploy.

**Comment by sparkiegeek** [comment]
The key idea here is (still) that

1) The UI makes a search and gets back a list of machines, grouped and sorted by user provided info
2) The backend executes the search and gets back a list of machines, and then sorts and groups them, sending back to the UI the grouped, sorted list and tracking the ids of the machines that are on the page
3) The UI renders the search result

Now something changes to one of the machines in the working set. As before:

4) The backend notifies the UI that machine `foo` has changed
5) The UI requests info about machine `foo`, and updates the view with the new info for `foo`

The change to fix this bug is that additionally, due to the change in 4) potentially reflecting a change in the group that `foo` belongs in, we need

6) The UI asks the backend to search for (pseudo) `[machine.id for machine in machines], group_by=..., sort_key=..., sort_order=...` 

Then re-do step 3) and apply the new grouping for all the machines in view (which will put `foo` in the right place).

It's important that the UI only search for the machine ids, so that it doesn't risk changing the working set
